### ISSUE TITLE
Provide example on how to create users in tenant chart

### ISSUE THREAD

**Issue by aqeelat** [minio/docs#1362]
The docs say that it is a list of secrets. It does not say that the list should be of objects that contain a name.

I had to go through the crd schema to understand why my tenant was not being created.

Incorrect:
```yaml
tenant:
  users:
    - my-user
```

Correct:
```yaml
tenant:
  users:
    - name: my-user
```
