### ISSUE TITLE
Request How to run distributed MinIO in Docker swarm with Træfɪk loadbalancer v2

### ISSUE THREAD

**Issue by irulvam** [minio/docs#287]
i try to configure with new version of traefik LB v2 on docker swarm, but its not running. please add example for that. thanks

**Comment by harshavardhana** [comment]
@irulvam feel free to send a PR yourself

**Comment by irulvam** [comment]
from https://docs.traefik.io/migration/v1-to-v2/
i try to change from your code. for example
```

version: '3.7'

services:
  cdna1:
    image: minio/minio:RELEASE.2020-03-25T07-03-04Z
    hostname: cdna1
    volumes:
      - cdna1-data:/export
    ports:
      - "9001:9000"
    networks:
      - cdna_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.cdna1==true
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.cdna.rule=Host(`cdna.local`)"
        - "traefik.http.services.cdna.loadbalancer.server.port=9000"
    command: server http://cdna{1...4}/export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  cdna2:
    image: minio/minio:RELEASE.2020-03-25T07-03-04Z
    hostname: cdna2
    volumes:
      - cdna2-data:/export
    ports:
      - "9002:9000"
    networks:
      - cdna_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.cdna2==true
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.cdna.rule=Host(`cdna.local`)"
        - "traefik.http.services.cdna.loadbalancer.server.port=9000"
    command: server http://cdna{1...4}/export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  cdna3:
    image: minio/minio:RELEASE.2020-03-25T07-03-04Z
    hostname: cdna3
    volumes:
      - cdna3-data:/export
    ports:
      - "9003:9000"
    networks:
      - cdna_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.cdna3==true
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.cdna.rule=Host(`cdna.local`)"
        - "traefik.http.services.cdna.loadbalancer.server.port=9000"
    command: server http://cdna{1...4}/export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  cdna4:
    image: minio/minio:RELEASE.2020-03-25T07-03-04Z
    hostname: cdna4
    volumes:
      - cdna4-data:/export
    ports:
      - "9004:9000"
    networks:
      - cdna_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.cdna4==true
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.cdna.rule=Host(`cdna.local`)"
        - "traefik.http.services.cdna.loadbalancer.server.port=9000"
    command: server http://cdna{1...4}/export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
	  
  cdnaproxy:
    image: traefik:v2.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      -  cdna_distributed
    ports:
      - 81:80
      - 8081:8080
    deploy:
      placement:
        constraints: 
          - node.role==manager
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.watch=true"

volumes:
  cdna1-data:
  
  cdna2-data:
  
  cdna3-data:
  
  cdna4-data:

networks:
  cdna_distributed:
    driver: overlay

secrets:
  secret_key:
    external: true
  access_key:
    external: true

```

this result

![image](https://user-images.githubusercontent.com/1930306/79829483-67ba0500-83cd-11ea-8f73-54b20be556b9.png)
